version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/devusSs/minly/internal/version.Version={{.Version}}
      - -X github.com/devusSs/minly/internal/version.Commit={{.Commit}}
      - -X github.com/devusSs/minly/internal/version.Date={{.Date}}

  - id: windows-amd64
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/devusSs/minly/internal/version.Version={{.Version}}
      - -X github.com/devusSs/minly/internal/version.Commit={{.Commit}}
      - -X github.com/devusSs/minly/internal/version.Date={{.Date}}

  - id: darwin-amd64
    env: [CGO_ENABLED=0]
    goos: [darwin]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/devusSs/minly/internal/version.Version={{.Version}}
      - -X github.com/devusSs/minly/internal/version.Commit={{.Commit}}
      - -X github.com/devusSs/minly/internal/version.Date={{.Date}}

  - id: darwin-arm64
    env: [CGO_ENABLED=0]
    goos: [darwin]
    goarch: [arm64]
    ldflags:
      - -s -w
      - -X github.com/devusSs/minly/internal/version.Version={{.Version}}
      - -X github.com/devusSs/minly/internal/version.Commit={{.Commit}}
      - -X github.com/devusSs/minly/internal/version.Date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"